#!/bin/bash
# Quick command reference for GeoterRA API Documentation

cat << 'EOF'
╔══════════════════════════════════════════════════════════════════════════════╗
║                 GeoterRA API Documentation - Quick Reference                 ║
╚══════════════════════════════════════════════════════════════════════════════╝

📚 DOCUMENTATION GENERATION COMMANDS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

✨ Generate Everything (Recommended)
  cd docApiWebsite
  npm run generate-all-docs
  
  This will:
  1. Generate OpenAPI spec from PHP annotations
  2. Convert OpenAPI to Markdown docs
  3. Build the complete documentation site

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

🔧 Individual Steps

Generate API spec only:
  cd API
  composer generate-api-docs
  ➜ Creates: API/public/openapi.json

Generate Markdown docs from OpenAPI:
  cd docApiWebsite
  npm run generate-api-docs
  ➜ Creates: docs/api/index.mdx and docs/api/schemas.mdx

Build documentation site:
  cd docApiWebsite
  npm run build
  ➜ Creates: build/ directory with static HTML

Serve documentation locally:
  cd docApiWebsite
  npm run serve
  ➜ Open: http://localhost:3000

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

📝 UPDATING DOCUMENTATION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

When you modify PHP code (controllers, DTOs):

1. Edit your Controller or DTO files
   Example: API/src/Controllers/AnalysisRequestController.php
   
2. Update OpenAPI annotations
   @OA\Post(), @OA\Schema(), @OA\Property(), etc.
   
3. Regenerate documentation
   cd docApiWebsite
   npm run generate-all-docs

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

📁 KEY FILES & DIRECTORIES
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

API Backend
├── src/Controllers/        → Endpoint definitions (@OA\Get, @OA\Post, etc)
├── src/DTO/               → Request/response schemas (@OA\Schema)
├── src/Core/              → OpenApiConfig.php (global metadata)
├── public/openapi.json    → Generated OpenAPI 3.0.0 spec [DO NOT EDIT]
└── composer.json          → Contains "generate-api-docs" script

Documentation Website (docApiWebsite)
├── docs/
│   ├── api/               → Auto-generated API documentation
│   └── *.md               → Manual documentation pages
├── scripts/
│   └── generate.mjs       → Converts OpenAPI → Markdown
├── build/                 → Static HTML (generated by npm run build)
└── package.json           → npm scripts

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

⚙️ CUSTOMIZATION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

To customize API documentation generation:

Edit: docApiWebsite/scripts/generate.mjs
- Change output format
- Add custom sections
- Modify schema display

To customize Docusaurus appearance:

Edit: docApiWebsite/docusaurus.config.js
- Branding (title, logo, colors)
- Navigation menu
- Footer information

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

✅ VERIFICATION CHECKLIST
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

✓ OpenAPI spec generated
  ls -lh API/public/openapi.json

✓ API documentation created
  ls -lh docApiWebsite/docs/api/

✓ Documentation built
  ls -lh docApiWebsite/build/

✓ Composer script configured
  grep "generate-api-docs" API/composer.json

✓ NPM scripts configured
  grep "generate-api-docs" docApiWebsite/package.json

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

🆘 TROUBLESHOOTING
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Issue: "Skipping unknown" warnings from OpenAPI generator
Fix:   Make sure composer.json autoload section is correct
       Then run: composer dump-autoload

Issue: openapi.json is empty (only {"openapi": "3.0.0"})
Fix:   Install doctrine/annotations:
       cd API
       composer require doctrine/annotations:^2.0

Issue: generated docs don't show in build
Fix:   Clear cache and rebuild:
       cd docApiWebsite
       npm run clear
       npm run generate-all-docs

Issue: Node version error
Fix:   Check version (need v20+):
       node --version
       Then upgrade if needed

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

📖 FOR MORE INFORMATION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

See the detailed setup guide:
  cat API_DOCUMENTATION_SETUP.md

Or check individual files:
  cat API/src/Core/OpenApiConfig.php         → Global OpenAPI config
  cat API/src/DTO/AnalysisRequestDTO.php     → Example DTO schema
  cat API/src/Controllers/AnalysisRequestController.php  → Example endpoints
  cat docApiWebsite/scripts/generate.mjs        → API→Markdown generator

EOF
